export const units =[ 
    {
        "name": "Drone",
        "race": "Zerg",
        "abilities": "Gather, Build, Advanced Build",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "50m, 0g",
        "supply": "1",
        "hit_points": "40",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "5(+1)",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "4.7",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0.1",
        "attack_cd": "1.07",
        "size": "0.75",
        "vision_distance": "8",
        "speed": "3.94",
        "cargo": "1",
        "build_time": "12",
        "img": "/img/unit01.png"
    },
    {
        "name": "Zergling",
        "race": "Zerg",
        "abilities": "Morph to Baneling",
        "Upgrades": "Adrenal Glands, Metabolic Boost",
        "attributes": "biological, light",
        "cost": "25m, 0g",
        "supply": "0.5",
        "hit_points": "35",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "5(+1)",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "10(+2), 14.1(+2.82)",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0.1",
        "attack_cd": "0.497(0.354)",
        "size": "0.75",
        "vision_distance": "8",
        "speed": "4.13(+2.45), 5.37(+3.18)",
        "cargo": "1",
        "build_time": "17",
        "img": "/img/unit02.png"
    },
    {
        "name": "Baneling",
        "race": "Zerg",
        "abilities": "Explode, Enable Building Attack, Disable Building Attack",
        "Upgrades": "Centrifugal Hooks",
        "attributes": "biological",
        "cost": "25m, 25g",
        "supply": "0.5",
        "hit_points": "30(+5)",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "20(+2)",
        "a_attack": "0",
        "attack_mod": "splash",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "+15(+2)light, +60(+3)structure",
        "range": "0.25, 2.20(aoe)",
        "attack_cd": "0",
        "size": "0.75",
        "vision_distance": "8",
        "speed": "3.5(+0.63), 4.55(+0.82)",
        "cargo": "1",
        "build_time": "14",
        "img": "/img/unit03.png"
    },
    {
        "name": "Hyrdralisk",
        "race": "Zerg",
        "abilities": "Morph into Lurker",
        "Upgrades": "Muscular Augments, Grooved Spines",
        "attributes": "biological, light",
        "cost": "100m, 50g",
        "supply": "2",
        "hit_points": "90",
        "armor": "0(+1)",
        "shields": "0",      
        "energy": "0",
        "g_attack": "12(+1)",
        "a_attack": "12(+1)",
        "attack_mod": "projectile",
        "g_dps": "22.2(+1.85)",
        "a_dps": "22.2(+1.85)",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "5(+1)",
        "attack_cd": "0.54",
        "size": "1.25",
        "vision_distance": "9",
        "speed": "3.15(+0.7875), 4.09(+0.0275)",
        "cargo": "2",
        "build_time": "24",
        "img": "/img/unit04.png"
    },
    {
        "name": "Infestor",
        "race": "Zerg",
        "abilities": "Neural Parasite, Fungal Growth, Microbial Shroud",
        "Upgrades": "none",
        "attributes": "biological, armored, psionic",
        "cost": "100m, 150g",
        "supply": "2",
        "hit_points": "90",
        "armor": "0",
        "shields": "0",
        "energy": "50(+25)/200",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "0",
        "size": "1.5",
        "vision_distance": "10",
        "speed": "3.15, 4.095",
        "cargo": "2",
        "build_time": "36",
        "img": "/img/unit05.png"
    },
    {
        "name": "Locust",
        "race": "Zerg",
        "abilities": "none",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "0m, 0g",
        "supply": "0",
        "hit_points": "50",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "10(+1)",
        "a_attack": "0",
        "attack_mod": "projectile",
        "g_dps": "23.25(+2.33)",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "3",
        "attack_cd": "0.43",
        "size": "0.75",
        "vision_distance": "6",
        "speed": "2.62, 3.66",
        "cargo": "-",
        "build_time": "3.6",
        "img": "/img/unit06.png"
    }
    ,
    {
        "name": "Overlord",
        "race": "Zerg",
        "abilities": "Morph to Overseer, Generate Creep, Mutate Ventral Sacs",
        "Upgrades": "Pneumatized Carapace",
        "attributes": "biological, armored",
        "cost": "100m, 0g",
        "supply": "2",
        "hit_points": "200",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "0",
        "size": "2",
        "vision_distance": "11",
        "speed": "0.902(+1.728)",
        "cargo": "-",
        "build_time": "18",
        "img": "/img/unit07.png"
    },
    {
        "name": "Changeling",
        "race": "Zerg",
        "abilities": "Disguise",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "0m, 0g",
        "supply": "0",
        "hit_points": "5",
        "armor": "0",
        "shields": "0",
        "energy": "0",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "0",
        "size": "0.75",
        "vision_distance": "8(9)",
        "speed": "3.15(4.13)",
        "cargo": "-",
        "build_time": "1",
        "img": "/img/unit08.png"
    },
    {
        "name": "Mutalisk",
        "race": "Zerg",
        "abilities": "Tissue Regeneration",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "100m, 100g",
        "supply": "2",
        "hit_points": "120",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "9(+1)",
        "a_attack": "9(+1)",
        "attack_mod": "projectile, bounce",
        "g_dps": "8.3(+0.92)",
        "a_dps": "8.3(+0.92)",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "3",
        "attack_cd": "1.09",
        "size": "1",
        "vision_distance": "11",
        "speed": "5.6",
        "cargo": "-",
        "build_time": "24",
        "img": "/img/unit09.png"
    }
]