export const units =[ 
    //Zerg
    {
        "name": "Baneling",
        "race": "Zerg",
        "abilities": "Explode, Enable Building Attack, Disable Building Attack",
        "Upgrades": "Centrifugal Hooks",
        "attributes": "biological",
        "cost": "25m, 25g",
        "supply": "0.5",
        "hit_points": "30(+5)",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "20(+2)",
        "a_attack": "0",
        "attack_mod": "splash",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "+15(+2)light, +60(+3)structure",
        "range": "0.25, 2.20(aoe)",
        "attack_cd": "0",
        "size": "0.75",
        "vision_distance": "8",
        "speed": "3.5(+0.63), 4.55(+0.82)",
        "cargo": "1",
        "build_time": "14",
        "img": "/img/unit03.png"
    },
    {
        "name": "Brood Lord",
        "race": "Zerg",
        "abilities": "Swarm Seeds",
        "Upgrades": "none",
        "attributes": "biological, armored, massive",
        "cost": "150m, 150g",
        "supply": "4",
        "hit_points": "225",
        "armor": "1(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "20(+2)",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "11.2(+1.12)",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "10",
        "attack_cd": "1.79",
        "size": "2",
        "vision_distance": "12",
        "speed": "1.97",
        "cargo": "-",
        "build_time": "24",
        "img": "/img/unit12.png"
    },
    {
        "name": "Broodling",
        "race": "Zerg",
        "abilities": "none",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "0m, 0g",
        "supply": "0",
        "hit_points": "30",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "4(+1)",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "8.7(+2.17)",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0.1",
        "attack_cd": ".46",
        "size": "1",
        "vision_distance": "7",
        "speed": "5.37",
        "cargo": "-",
        "build_time": "1",
        "img": "/img/unit10.png"
    },
    {
        "name": "Changeling",
        "race": "Zerg",
        "abilities": "Disguise",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "0m, 0g",
        "supply": "0",
        "hit_points": "5",
        "armor": "0",
        "shields": "0",
        "energy": "0",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "0",
        "size": "0.75",
        "vision_distance": "8(9)",
        "speed": "3.15(4.13)",
        "cargo": "-",
        "build_time": "1",
        "img": "/img/unit08.png"
    },
    {
        "name": "Corruptor",
        "race": "Zerg",
        "abilities": "Caustic Spray, Morph to Brood Lord",
        "Upgrades": "none",
        "attributes": "biological, armored",
        "cost": "150m, 100g",
        "supply": "2",
        "hit_points": "200",
        "armor": "2(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "0",
        "a_attack": "14(+1)",
        "attack_mod": "projectile",
        "g_dps": "0",
        "a_dps": "10.3(+0.74)",
        "bonus_dps": "+4.4(+0.74)Ma",
        "bonus": "+6(+1)Ma",
        "range": "6",
        "attack_cd": "1.36",
        "size": "1.25",
        "vision_distance": "10",
        "speed": "4.725",
        "cargo": "-",
        "build_time": "29",
        "img": "/img/unit13.png"
    },
    {
        "name": "Drone",
        "race": "Zerg",
        "abilities": "Gather, Build, Advanced Build",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "50m, 0g",
        "supply": "1",
        "hit_points": "40",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "5(+1)",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "4.7",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0.1",
        "attack_cd": "1.07",
        "size": "0.75",
        "vision_distance": "8",
        "speed": "3.94",
        "cargo": "1",
        "build_time": "12",
        "img": "/img/unit01.png"
    },
    {
        "name": "Hyrdralisk",
        "race": "Zerg",
        "abilities": "Morph into Lurker",
        "Upgrades": "Muscular Augments, Grooved Spines",
        "attributes": "biological, light",
        "cost": "100m, 50g",
        "supply": "2",
        "hit_points": "90",
        "armor": "0(+1)",
        "shields": "0",      
        "energy": "0",
        "g_attack": "12(+1)",
        "a_attack": "12(+1)",
        "attack_mod": "projectile",
        "g_dps": "22.2(+1.85)",
        "a_dps": "22.2(+1.85)",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "5(+1)",
        "attack_cd": "0.54",
        "size": "1.25",
        "vision_distance": "9",
        "speed": "3.15(+0.7875), 4.09(+0.0275)",
        "cargo": "2",
        "build_time": "24",
        "img": "/img/unit04.png"
    },
    {
        "name": "Infestor",
        "race": "Zerg",
        "abilities": "Neural Parasite, Fungal Growth, Microbial Shroud",
        "Upgrades": "none",
        "attributes": "biological, armored, psionic",
        "cost": "100m, 150g",
        "supply": "2",
        "hit_points": "90",
        "armor": "0",
        "shields": "0",
        "energy": "50(+25)/200",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "0",
        "size": "1.5",
        "vision_distance": "10",
        "speed": "3.15, 4.095",
        "cargo": "2",
        "build_time": "36",
        "img": "/img/unit05.png"
    },
    {
        "name": "Zergling",
        "race": "Zerg",
        "abilities": "Morph to Baneling",
        "Upgrades": "Adrenal Glands, Metabolic Boost",
        "attributes": "biological, light",
        "cost": "25m, 0g",
        "supply": "0.5",
        "hit_points": "35",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "5(+1)",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "10(+2), 14.1(+2.82)",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0.1",
        "attack_cd": "0.497(0.354)",
        "size": "0.75",
        "vision_distance": "8",
        "speed": "4.13(+2.45), 5.37(+3.18)",
        "cargo": "1",
        "build_time": "17",
        "img": "/img/unit02.png"
    },
    {
        "name": "Larva",
        "race": "Zerg",
        "abilities": "none",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "0m, 0g",
        "supply": "0",
        "hit_points": "25",
        "armor": "10",
        "shields": "0",
        "energy": "0",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "",
        "size": "0.25",
        "vision_distance": "5",
        "speed": "0",
        "cargo": "-",
        "build_time": "-",
        "img": "/img/unit14.png"
    },
    {
        "name": "Locust",
        "race": "Zerg",
        "abilities": "none",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "0m, 0g",
        "supply": "0",
        "hit_points": "50",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "10(+1)",
        "a_attack": "0",
        "attack_mod": "projectile",
        "g_dps": "23.25(+2.33)",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "3",
        "attack_cd": "0.43",
        "size": "0.75",
        "vision_distance": "6",
        "speed": "2.62, 3.66",
        "cargo": "-",
        "build_time": "3",
        "img": "/img/unit06.png"
    },
    {
        "name": "Lurker",
        "race": "Zerg",
        "abilities": "none",
        "Upgrades": "Adaptive Talons, Seismic Spines",
        "attributes": "biological, armored",
        "cost": "50m, 100g",
        "supply": "3",
        "hit_points": "200",
        "armor": "1(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "20(+2)",
        "a_attack": "0",
        "attack_mod": "linear/lined",
        "g_dps": "13.99(+14)",
        "a_dps": "0",
        "bonus_dps": "+6.99(+0.7)A",
        "bonus": "+10(+1)A",
        "range": "8(+2)",
        "attack_cd": "1.43",
        "size": "1.5",
        "vision_distance": "10",
        "speed": "4.13(+0.413), 5.37(+0.537)",
        "cargo": "4",
        "build_time": "18",
        "img": "/img/unit15.png"
    },
    {
        "name": "Mutalisk",
        "race": "Zerg",
        "abilities": "Tissue Regeneration",
        "Upgrades": "none",
        "attributes": "biological, light",
        "cost": "100m, 100g",
        "supply": "2",
        "hit_points": "120",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "9(+1)",
        "a_attack": "9(+1)",
        "attack_mod": "projectile, bounce",
        "g_dps": "8.3(+0.92)",
        "a_dps": "8.3(+0.92)",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "3",
        "attack_cd": "1.09",
        "size": "1",
        "vision_distance": "11",
        "speed": "5.6",
        "cargo": "-",
        "build_time": "24",
        "img": "/img/unit09.png"
    },
    {
        "name": "Nydus Worm",
        "race": "Zerg",
        "abilities": "Load",
        "Upgrades": "none",
        "attributes": "biological, armored, structure",
        "cost": "75m, 75g",
        "supply": "0",
        "hit_points": "300",
        "armor": "1(+2)",
        "shields": "0",
        "energy": "0",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "0",
        "size": "3x3",
        "vision_distance": "10",
        "speed": "0",
        "cargo": "-",
        "build_time": "14",
        "img": "/img/unit16.png"
    },
    {
        "name": "Overlord",
        "race": "Zerg",
        "abilities": "Morph to Overseer, Generate Creep, Mutate Ventral Sacs",
        "Upgrades": "Pneumatized Carapace",
        "attributes": "biological, armored",
        "cost": "100m, 0g",
        "supply": "0",
        "hit_points": "200",
        "armor": "0(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "0",
        "size": "2",
        "vision_distance": "11",
        "speed": "0.902(+1.728)",
        "cargo": "-",
        "build_time": "18",
        "img": "/img/unit07.png"
    },
    {
        "name": "Overseer",
        "race": "Zerg",
        "abilities": "Oversight, Detector, Spawn Changeling, Contaminate",
        "Upgrades": "Pneumatized Carapace",
        "attributes": "biological, armored, detector",
        "cost": "50m, 50g",
        "supply": "0",
        "hit_points": "200",
        "armor": "1(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "0",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "0",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "0",
        "attack_cd": "0",
        "size": "2",
        "vision_distance": "11",
        "speed": "2.62(+2.1)",
        "cargo": "-",
        "build_time": "12",
        "img": "/img/unit17.png"
    },
    {
        "name": "Queen",
        "race": "Zerg",
        "abilities": "Spawn Larva, Spawn Creep Tumor, Transfusion",
        "Upgrades": "none",
        "attributes": "biological, Psionic",
        "cost": "150m, 0g",
        "supply": "2",
        "hit_points": "175",
        "armor": "1(+1)",
        "shields": "0",
        "energy": "25/200",
        "g_attack": "9(+1)",
        "a_attack": "9(+1)",
        "attack_mod": "projectile",
        "g_dps": "12.6(+1.4)",
        "a_dps": "12.6(+1.4)",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "8",
        "attack_cd": "0.71",
        "size": "1",
        "vision_distance": "9",
        "speed": "1.31, 3.5",
        "cargo": "2",
        "build_time": "36",
        "img": "/img/unit11.png"
    },
    {
        "name": "Ravager",
        "race": "Zerg",
        "abilities": "Corrosive Bile",
        "Upgrades": "none",
        "attributes": "biological",
        "cost": "25m, 75g",
        "supply": "2",
        "hit_points": "120",
        "armor": "1(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "16(+2)",
        "a_attack": "",
        "attack_mod": "none",
        "g_dps": "14(+1.75)",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "6",
        "attack_cd": "1.14",
        "size": "1.5",
        "vision_distance": "9",
        "speed": "3.85, 5",
        "cargo": "4",
        "build_time": "9",
        "img": "/img/unit18.png"
    },
    {
        "name": "Roach",
        "race": "Zerg",
        "abilities": "Rapid Regeneration, Morph to Ravager",
        "Upgrades": "Glial Reconstitution, Tunneling Claws",
        "attributes": "biological, armored",
        "cost": "75m, 25g",
        "supply": "2",
        "hit_points": "145",
        "armor": "1(+1)",
        "shields": "0",
        "energy": "0",
        "g_attack": "16(+2)",
        "a_attack": "",
        "attack_mod": "none",
        "g_dps": "11.2(+1.4)",
        "a_dps": "0",
        "bonus_dps": "0",
        "bonus": "0",
        "range": "4",
        "attack_cd": "1.43",
        "size": "1",
        "vision_distance": "9",
        "speed": "3.15(+1.05), 4.09(+1.36)",
        "cargo": "2",
        "build_time": "19",
        "img": "/img/unit19.png"
    },

    //Protoss    
    {
        "name": "Adept",
        "race": "Protoss",
        "abilities": "Psionic Transfer",
        "Upgrades": "Resonating Glaives",
        "attributes": "biological, light",
        "cost": "100m, 25g",
        "supply": "2",
        "hit_points": "70",
        "armor": "1(+1)",
        "shields": "70",
        "energy": "0",
        "g_attack": "10(+1)",
        "a_attack": "0",
        "attack_mod": "none",
        "g_dps": "6.2(+0.62), 15.6(+1.56)",
        "a_dps": "0",
        "bonus_dps": "+7.45(+0.62)L",
        "bonus": "+12(+1)L",
        "range": "4",
        "attack_cd": "1.61, 0.64",
        "size": "1",
        "vision_distance": "9, 4",
        "speed": "3.5",
        "cargo": "2",
        "build_time": "27/20",
        "img": "/img/unit25.png"
    }
]